### ISSUE TITLE
Single table inheritance

### ISSUE THREAD

**Issue by MylesKingsnorth01** [DamienHarper/DoctrineAuditBundle#73] opened 2019-08-16 14:27 UTC
I have an abstract entity which uses single table inheritance. Using a discriminator map, I'm mapping 3 entities that extend my abstract entity. 

In my `dh_doctrine_audit.yaml` under entities, I've put my parent class. Whenever I change one of the subclasses, no audits are created. I also did try splitting my audit config out by including the 3 entities individually. 

Here is my yaml config:

```yaml
dh_doctrine_audit:
    table_prefix: 'audit_'
    table_suffix: ''

    ignored_columns:
        - created
        - updated
        - createdBy
        - updatedBy

    entities:
        App\Entity\AbstractFooBar: ~
```

Here is the parent class:

```php
/**
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *     "example_one" = "ExampleOne",
 *     "example_two" = "ExampleTwo",
 *     "example_three" = "ExampleThree"
 * })
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 */
abstract class AbstractFooBar
{
    // ...
}
```

And then my three entities look like this:

```php
/**
 * @Entity()
 */
class ExampleOne extends AbstractFooBar
{
    // ...
}
```

Looking through the source code, there appears to be logic to audit these entities.

**Comment by DamienHarper** [comment] 2019-08-19 11:40
@MylesKingsnorth01 Thanks for the report, I will look at this asap.

**Comment by DamienHarper** [comment] 2019-08-29 13:31
@MylesKingsnorth01 it should work if you add each child entity that extend your abstract entity to the `dh_doctrine_audit.yaml` configuration file.

**Comment by DamienHarper** [comment] 2019-09-06 15:28
As long as I can't reproduce the issue and no feedback is provided, I close this issue. 
@MylesKingsnorth01 Feel free to reopen if needed.

**Comment by MylesKingsnorth01** [comment] 2019-09-27 10:56
Sorry for not getting back to this in a while. 

So as you've said, I added all child entities to my configuration. When I update one of the child entities, the audit shows for all children. Is that the intended behaviour? It's a bit misleading.

**Comment by DamienHarper** [comment] 2019-09-27 13:25
Hi @MylesKingsnorth01, well it is not the intended behavior and looks like a bug, I re-open the issue and will have a look at it.

**Comment by DamienHarper** [comment] 2019-09-27 17:17
@MylesKingsnorth01 I think I misunderstood what you meant: the current behavior is intended.

Single table inheritance in Doctrine means that you use one table (let's call it root table) to store different entities, all sharing the same root. The root table has a column dedicated to identify which entity a record belongs to (discriminator column).
So when you create/modify a child entity, it is stored in the root table with a specific discriminator value.
Also, as a consequence, the bundle handles an audit table for the root table (only) which means that by configuring child entities to be audited, their audit operations (inserts into audits) are done against the audit table of the root table (only). 

Currently there is no way to know if an audit record belongs to a child entity or the root one so no way to filter them out in `AuditReader::getAudits()`.

I need to find/decide if and how to manage this.

**Comment by DamienHarper** [comment] 2019-09-30 08:55
@MylesKingsnorth01 I've implemented the missing part of the inheritance support. Can you please test `master` branch? 
Note: run the `bin/console audit:schema:update` command if you already have audit tables.

**Comment by MylesKingsnorth01** [comment] 2019-09-30 11:09
@DamienHarper Thanks for taking a look. I can confirm that your update works as expected. I tested a couple scenarios and they all worked. Thanks for adding the missing part.

**Closed** 2019-09-30 11:16 UTC
