### ISSUE TITLE
Bug in pagination when viewing one entity

### ISSUE THREAD

**Issue by matthijsch** [DamienHarper/DoctrineAuditBundle#162] opened 2020-01-08 14:45 UTC
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.2.3
| PHP version                 | 7.3.13
| Database                    | MySQL

When viewing the audits for one entity which has multiple pages the pagination links are broken because the entity ID isn't passed to the paths

**Comment by DamienHarper** [comment] 2020-01-08 15:25
@matthijsch thanks for the report. May you have a chance to test `master` branch? 
Some fixes have been pushed since the latest release.

**Comment by DamienHarper** [comment] 2020-01-08 15:29
@matthijsch I've just tested and the issue is still present in `master` branch. I'll fix this asap.

**Comment by DamienHarper** [comment] 2020-01-09 08:43
@matthijsch I pushed a fix on `master` branch. May you have a chance to test `master` branch and provide me some feedback?

**Comment by DamienHarper** [comment] 2020-01-15 22:11
@matthijsch I close the issue for now. Re-open it if needed

**Closed by DamienHarper** 2020-01-15 22:11 UTC
Labels: bug

**Comment by DamienHarper** [comment] 2020-02-06 23:24
@matthijsch 3.3.0 is released
