### ISSUE TITLE
Float entries. Dissociate id source

### ISSUE THREAD

**Issue by tleurida2** [DamienHarper/DoctrineAuditBundle#7] opened 2018-05-09 12:49 UTC
Float entries detected as update even if there is no change.
Dissociate id source was wrong.

[AuditSubscriber.zip](https://github.com/DamienHarper/DoctrineAuditBundle/files/1987837/AuditSubscriber.zip)

**Comment by DamienHarper** [comment] 2018-05-28 22:09
@tleurida2, thanks for your feedback and sorry for my late reply.
You're right about updates detected by error regarding float/int but your solution likely won't work with boolean/null values (null == false). Maybe you could provide a PR?
For the other part (dissociate id source was wrong), could you provide an example?

**Comment by DamienHarper** [comment] 2018-06-21 23:47
I pushed some changes that should fix the issue. Could you please test against master branch?

**Comment by codedmonkey** [comment] 2018-06-22 12:51
For us, the issue is that Doctrine returns the values of decimals as `string`, understandably, since you can set a specific `precision` which would be lost as `float` type. When editing a decimal field in the Form component, it does return a `float`. So when comparing old and new, Doctrine sees a change in the typing, not in contents.

We're choosing to conform to Doctrine in this case by changing our fields to a `string` before setting them on the entity.

**Comment by Maxdw** [comment] 2018-06-27 09:38
Our problem was that Symfony's FormBuilder built-in MoneyType transforms values to the float type. While our entity's corresponding decimal field setters and getters did not enforce the string type it should have (decimals should not be represented by floats). By typehinting these getters and setters with the string type you can enforce the decimal field to be represented as a string, even if a float value is used to set the field. Then when the audit bundle does the difference comparison it won't try to compare the float as it was set to the entity with the string decimal that came from the database.

**Comment by DamienHarper** [comment] 2018-07-24 16:30
Decimals are now casted as string before comparison. Can you please test against dev-master?

**Comment by DamienHarper** [comment] 2018-07-29 09:02
Closing the issue for now. Feel free to re-open if needed.

**Closed by DamienHarper** 2018-07-29 09:02 UTC
