### ISSUE TITLE
Unknown "spaceless" filter.

### ISSUE THREAD

**Issue by balvirsingh** [DamienHarper/DoctrineAuditBundle#65] opened 2019-05-22 13:32 UTC
I installed this bundle on Symfony 4.2, the mentioned below issue is occurring.

Unknown "spaceless" filter.

if I remove it from twig file, then works fine.

Please provide the solution or tell me how to override the twig.

**Comment by DamienHarper** [comment] 2019-05-22 20:09
@balvirsingh thanks for your feedback, the spaceless tag is deprecated since Twig 1.38 in favor of the spaceless filter. What version of Twig is installed in your application?

**Comment by balvirsingh** [comment] 2019-05-23 07:07
symfony/twig-bundle - v4.2.2  Symfony TwigBundle
twig/twig - v2.6.2  Twig, the flexible, fast, and secure template language for PHP

So, it's 2.6.2.

**Comment by balvirsingh** [comment] 2019-05-23 09:39
Or can I override the template?

One more issue:-
When I call mentioned below method in my controller's function, it gives an error

$reader = $this->container->get('dh_doctrine_audit.reader');

**Comment by balvirsingh** [comment] 2019-05-24 06:26
Hi,

I have added some more details about it, Please check these and let me know
if issue can be resolved?

**Comment by DamienHarper** [comment] 2019-05-24 06:48
@balvirsingh That's quite weird. I need some more time to identify/reproduce the issue. Meanwhile, you can override the template and remove the spaceless filter call.

Regarding the reader service, you should be able to inject it in a constructor/method, for example:
```php
public function getHistory(AuditReader $reader, string $entity, string $id, int $page = 1, int $pageSize = 500): Response
{
    // ...
}
```
Where do you try to access the reader: from a controller? from a command?

**Comment by balvirsingh** [comment] 2019-05-24 06:53
Yes, I am trying to access in the controller.

**Comment by DamienHarper** [comment] 2019-05-24 07:25
@balvirsingh can you post what your controller inherits from?

**Comment by balvirsingh** [comment] 2019-05-24 07:29
`<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use App\Services\CoreService;
use App\Entity\Organizer;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;


class OrganizerController extends AbstractController
{   

    /**
     * To find list of organizers
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function list()
    {   
    
        $reader = $this->get('dh_doctrine_audit.reader');
        
        $data = $reader
             ->filterBy(AuditReader::UPDATE)   // add this to only get `update` entries.
             ->getAudit('App\Entity\Organizer', 10)
         ;

        return $this->render('organizer/list.html.twig', [
            'no_sidebar' => true,
            'data' => $data
        ]);
    }

}`

**Comment by balvirsingh** [comment] 2019-05-24 07:31
I just sent full controller code, pl check.

It would be good if you come available on skype or hangout for me.

Thanks & Regards,
Balvir

**Comment by DamienHarper** [comment] 2019-05-24 07:44
@balvirsingh your controller extends `AbstractController` which let you access a "limited" container that's why you cannot access the reader from there. The best solution for you here is to inject the reader service to your `OrganizerController::list()` method.

```php
public function list(AuditReader $reader)
{
    // ...
}
```

**Comment by balvirsingh** [comment] 2019-05-24 07:46
Hi @DamienHarper,

Great!, it works now on my system. Please work on the spaceless filter. I suggest you to please remove this filter from twig as its deprecated now.

Thank you so much.

**Comment by balvirsingh** [comment] 2019-06-11 12:22
Hi @DamienHarper,

Unknown "spaceless" filter.
Have you work
![image](https://user-images.githubusercontent.com/5753046/59271457-7e51e480-8c71-11e9-9cfe-7be7e972e1f3.png)

Have you worked on the above issue? Still, I am facing the same issue. I don't want to override the templates. Please remove that filter for me or do any other alternative to make it work. 

Thanks.

**Comment by balvirsingh** [comment] 2019-06-11 12:25
Hi Damien,

Please reply on my comment which I added on git.

Thanks.

**Comment by DamienHarper** [comment] 2019-06-11 14:52
@balvirsingh I have a job that keeps me very busy lately so I cannot work on this project all the time. Also, I am notified when an issue is opened/commented/closed as well as when a PR is opened/commented/declined/etc. so no need to comment + send an email + send a LinkedIn message, it won't make things happen faster. 

Please, test against `master` branch: spaceless filter is not used anymore but the spaceless tag is. I'll release a new version in the next days.

**Comment by balvirsingh** [comment] 2019-06-11 16:01
Hi @DamienHarper,

I sincerely apologize for bothering. I will be careful in future.

Thanks.

**Comment by DamienHarper** [comment] 2019-06-11 20:54
@balvirsingh let's forget it and move forward ;) 
does the `master` branch solve your issue?

**Comment by balvirsingh** [comment] 2019-06-12 09:17
Hi @DamienHarper,

Yes, it does work now, Thanks

**Comment by DamienHarper** [comment] 2019-06-12 09:18
@balvirsingh thanks for the feedback. 
I close this issue as the fix will be part of next release.

**Closed by DamienHarper** 2019-06-12 09:18 UTC
