### ISSUE TITLE
Can DoctrineAuditBundle work with related entities?

### ISSUE THREAD

**Issue by olek07** [DamienHarper/DoctrineAuditBundle#40] opened 2019-02-06 12:11 UTC
I have the entity

```
/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="case_core")
 */
class CoreCase {
         /**
	 * @ORM\Column(type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", name="type", length=50)
	 */
	private $type;

	/**
	 * @ORM\Column(type="string", name="status", length=50)
	 */
	private $status;
}
```
and the entity 
```
/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="case_diesel")
 */
class DieselCase {
	/**
	 * @ORM\Id
	 * @ORM\ManyToOne(targetEntity="CoreCase", cascade={"persist"})
	 * @ORM\JoinColumn(name="core_case", referencedColumnName="id")
	 */
	private $coreCase;
}
```

If I try to run this code, I get the exception 

> CRITICAL13:00:09 | request | Uncaught PHP Exception ErrorException: "Notice: Undefined index: coreCase" at /home/alexander/projects/lawbutler/vendor/damienharper/doctrine-audit-bundle/src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php line 384

```
$dieselCase = $em->getRepository(DieselCase::class)->find(1);
$dieselCase->setCreatedAt(new \DateTime('now'));
$em->flush();
```
What is the problem? Can the bundle properly work with related entities?

**Comment by DamienHarper** [comment] 2019-02-06 15:25
@olek07 Sure it does work with related entities.
To better understand your problem, can you please provide your `dh_doctrine_audit.yaml` content?
Also, `$coreCase` property in your `DieselCase` class has both the [`@ORM\Id`](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/annotations-reference.html#annref_id) annotation and the `@ORM\ManyToOne`. Isn't it a typo?

**Comment by DamienHarper** [comment] 2019-02-06 15:43
@olek07 after digging a bit into the code, the error you encounter comes from [`Type::getType($meta->fieldMappings[$pk]['type']);`](https://github.com/DamienHarper/DoctrineAuditBundle/blob/955af68b19f4a6da53e289e81a08fb159e18b99a/src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php#L384)

Here, `$meta` is Doctrine entity metadata (Doctrine stuff, no link with this bundle) and `$pk` is the primary key field of the entity (grabbed from Doctrine metadata -- Doctrine stuff, no link with this bundle either)

So I suspect something's wrong with your entities, probably a consequence of the fact that `$coreCase` field has both `@ORM\Id` and `@ORM\ManyToOne` annotations

**Comment by olek07** [comment] 2019-02-06 15:45
Ok. I will check it. My colleague said, we need this definition.

**Comment by DamienHarper** [comment] 2019-02-06 16:29
Ok, let me know about your findings. 
I think that the primary key of the `case_diesel` table should be another field annotated with `@ORM\Id`

Something like this:
```php
/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="case_diesel")
 */
class DieselCase {
	/**
	 * @ORM\Id
	 */
	private $id;

	/**
	 * @ORM\ManyToOne(targetEntity="CoreCase", cascade={"persist"})
	 * @ORM\JoinColumn(name="core_case", referencedColumnName="id")
	 */
	private $coreCase;
}
```

**Comment by olek07** [comment] 2019-02-07 09:47
We need `@ORM\Id`. The idea is to have the same id in the tables case_core and case_diesel. I mayn't remove this annotation, because Doctrine doesn't know how to treat this field.

**Comment by olek07** [comment] 2019-02-07 09:52
Und one more issue.
If I change `type` like this
```$dieselCase = $em->getRepository(DieselCase::class)->find(1);
$dieselCase->getCoreCase()->setType('%ddddd%');
```
this change is written neither into case_core_audit nor into case_diesel_audit

**Comment by DamienHarper** [comment] 2019-02-07 10:28
@olek07 I don't see a `flush()` call in your last example. Audits are populated at flush time.

**Comment by olek07** [comment] 2019-02-07 10:51
persist and flush are present. The changes were saved in the tables, but not in the audit tables

**Comment by DamienHarper** [comment] 2019-02-07 11:07
Something should have been logged to the `case_core_audit` table but I suppose the initial error is the reason why audits have not been saved.
I'll try to build a debug environment similar to yours to do some further debugging but It will take some time.

**Comment by DamienHarper** [comment] 2019-02-18 00:43
@olek07 could you please provide your `DieselCase` and `CoreCase` classes so that I can try to reproduce your use case please?

**Comment by DamienHarper** [comment] 2019-02-20 10:31
@olek07 I've just pushed a fix to support Identity through foreign Entities. It should fix your issue. 
Can you please test your code against `master` branch of this bundle and post some feedback?

**Comment by DamienHarper** [comment] 2019-03-01 09:03
@olek07 any news on this issue, did you had a chance to test the fix?

**Closed** 2019-03-04 16:34 UTC
