### ISSUE TITLE
Problem with the namespace of entities

### ISSUE THREAD

**Issue by Gonzalo1987** [DamienHarper/DoctrineAuditBundle#62] opened 2019-04-17 17:26 UTC
Hello!
I have been using your package since v1.2 and I like it a lot, but I had a problem with the routes because the characters '\' are in the namespace of my entities and the URLs.

The package creates routes such as:
http://localhost/myproject/public/audit/App\Entity\MyEntity
And I can not reach them. 

In the version 1.2, I modified the controller and the routes of the views changing the \ in favour of ##, and the trick succeded. But I've updated the bundle and I should make the change again (what is more I lack the DependencyInjector and my Custom Controller haven't the reader in the container).

It would be possible make the change in future versions (I guess that I could implement it, or you can implement a better solution if you wish), but I would prefer that I don't have to make changes about this in the next updates.

I'm sorry for my poor english, I want you to understand what I'm talking about, and thank you for this amazing bundle. 👍

**Comment by DamienHarper** [comment] 2019-04-17 21:23
@Gonzalo1987 thanks for your feedback but I don't really get what the problem is in your use case :/ 
What do you mean by "I can not reach them"? What is your current stack (OS, webserver, browser)?
FYI, backslashes in URL are urlencoded (automatically by Symfony) as `%5C` sequence (see [HTML URL Encoding Reference)](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiBm-KrhtjhAhWoxYUKHSsRB0MQFjAAegQIBBAB&url=https%3A%2F%2Fwww.w3schools.com%2Ftags%2Fref_urlencode.asp&usg=AOvVaw3PfD-bq8HVx-5Dbhw4Vyme)

**Comment by Gonzalo1987** [comment] 2019-04-17 21:36
Hi @DamienHarper, 
I am using Windows with Apache, it is easily reproducible using wamp64. Windows has problem with the backslashes in the routes. My project is using Symfony 4.x Thank you very much!

**Comment by DamienHarper** [comment] 2019-04-18 07:13
@Gonzalo1987 OK, it seems to be Windows specific, I'll have a look at this.

**Comment by Gonzalo1987** [comment] 2019-04-18 12:19
Thank you very much!

**Comment by DamienHarper** [comment] 2019-04-18 12:48
@Gonzalo1987 this is fixed on `master` branch. It will be available in upcoming 2.3.0 release.

**Closed by DamienHarper** 2019-04-18 12:48 UTC
