### ISSUE TITLE
Type Hinting incompatible with Symfony Interface

### ISSUE THREAD

**Issue by llaville** [DamienHarper/DoctrineAuditBundle#168] opened 2020-02-07 08:22 UTC
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.3.1
| PHP version                 | 7.3.14
| Symfony | 4.4.3
| Database                    | SQLite

#### Summary

 Compile Error: Declaration of DH\DoctrineAuditBundle\Routing\DoctrineAuditRoutingLoader::load($resource, ?string $type = NULL): 
 Symfony\Component\Routing\RouteCollection must be compatible with Symfony\Component\Config\Loader\LoaderInterface::load($resource, $type = NULL)

With Symfony 5.0 
https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Config/Loader/LoaderInterface.php#L28

With Symfony 4.4
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Config/Loader/LoaderInterface.php#L29

Beware of declare strict_types usage

**Comment by DamienHarper** [comment] 2020-02-07 08:27
@llaville Thanks for the report, will fix asap

**Comment by llaville** [comment] 2020-02-07 08:32
Then, 

Compile Error: Declaration of DH\DoctrineAuditBundle\Routing\DoctrineAuditRoutingLoader::supports($resource, ?string $type = NULL): bool 
must be compatible with Symfony\Component\Config\Loader\LoaderInterface::supports($resource, $type = NULL)

**Comment by DamienHarper** [comment] 2020-02-07 09:31
@llaville should be fixed right now in `3.3.2

**Comment by llaville** [comment] 2020-02-07 09:41
Confirmed. BC break solved. Thanks !

**Closed** 2020-02-07 09:41 UTC
Labels: bug

**Comment by colonelclick** [comment] 2020-05-23 00:01
Hi @DamienHarper,

This bug has returned in the master branch. Looking at the git history it looks like it was introduced on 4/1/2020. Is this an intentional move to drop support for Symfony < 5?

Thanks!

**Comment by colonelclick** [comment] 2020-05-23 00:26
@DamienHarper 

FYI this issue has resurfaced in master, but 3.4.1 is still working fine. I know master is not stable but I want to mention in case it is an accident because I think this means it can only be compatible with Symfony 5.

**Comment by benoit-hash** [comment] 2020-12-08 11:38
Hello @DamienHarper ,
I really want to thank you for your work.
This issue resurfaced in the auditor-bundle with Symfony 4.4.

**Comment by DamienHarper** [comment] 2020-12-08 15:00
@benoit-hash thanks for the report, `4.0.2` fixes that regression
