### ISSUE TITLE
Issue with softdeleteable entity with doctrine extension

### ISSUE THREAD

**Issue by hardiksinh** [DamienHarper/DoctrineAuditBundle#122] opened 2019-11-19 11:13 UTC
As mentioned in https://github.com/DamienHarper/DoctrineAuditBundle/issues/87
Soft-delete is not getting recorded in audit table of entity though deleted_at field updating and soft-delete filter works fine.

Extension I am using:
[https://github.com/Atlantic18/DoctrineExtensions](https://github.com/Atlantic18/DoctrineExtensions)

Symfony: 4.3.8

**Comment by DamienHarper** [comment] 2019-11-19 11:17
@hardiksinh I suppose you're using v3.0 of the bundle so you may use the configuration file only or both config file and annotations so could you post your `dh_doctrine_audit.yaml` file and eventually the annotations you use in your one of your entities (one that should be audited and has softdeletable behavior)

**Comment by hardiksinh** [comment] 2019-11-19 11:23
I haven't used annotation in user entity but used entity namespace in config file.

config\packages\dh_doctrine_audit.yaml
```
dh_doctrine_audit:
    # Configuration reference available at:
    # https://github.com/DamienHarper/DoctrineAuditBundle#configuration

    entities:
        App\Entity\User: ~
#        MyBundle\Entity\MyAuditedEntity1: null   # all MyAuditedEntity1 properties are audited
#        MyBundle\Entity\MyAuditedEntity2:
#            ignored_columns:                  # MyAuditedEntity2 properties to be ignored by the audit process
#                - createdAt
#                - updatedAt
```

**Comment by hardiksinh** [comment] 2019-11-19 12:54
Tried with using annotation in the Relationship entity but same issue. Add and update recorded but soft-delete not.

Relationship.php
```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use DH\DoctrineAuditBundle\Annotation as Audit;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RelationshipRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @Audit\Auditable
 */
class Relationship
{
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    public function setDeletedAt($deletedAt): self
    {
        $this->deletedAt = $deletedAt;
    }
```

Deleting in RelationshipController.php

``` 
        $relationship = $this->getDoctrine()
            ->getRepository(Relationship::class)
            ->find($id);

        $em = $this->getDoctrine()->getManager();
        $em->remove($relationship);
        $em->flush();
```

NOTE: I used LONGTEXT instead of JSON type in migrations of audit tables for diff column because MariaDB of my XAMPP is not supporting JSON field type.

DoctrineAuditBundle: 3.0.0
DoctrineExtensions: 2.4.26
MariaDB: 10.1.38
PHP version: 7.2.15
![Audit log of Relationship entity](https://user-images.githubusercontent.com/1895099/69148115-8ef86780-0af9-11ea-875d-374fac39f4ce.png)
![Soft-deleted record in table](https://user-images.githubusercontent.com/1895099/69148165-af282680-0af9-11ea-836a-bbdfc94bb10d.png)

**Comment by DamienHarper** [comment] 2019-11-19 13:22
Well that's weird. It might be that the softdelete listener is fired after the audit one. I need to investigate a bit more.

**Comment by DamienHarper** [comment] 2019-11-22 09:37
@hardiksinh can you try against `event-subscriber-priority` branch?
`composer require damienharper/doctrine-audit-bundle "dev-event-subscriber-priority"`

**Comment by DamienHarper** [comment] 2019-11-25 21:22
@hardiksinh did you had a chance to test `event-subscriber-priority` branch?

**Comment by hardiksinh** [comment] 2019-11-26 14:02
@DamienHarper Sorry I wasn't on this page. No, it does not fix issue.

**Comment by DamienHarper** [comment] 2019-11-26 16:15
@hardiksinh I have hard time to debug as long as I cannot reproduce the issue myself :/
Could you please share with me a sample project I could use to reproduce and try to fix the issue please?

**Comment by hardiksinh** [comment] 2019-11-27 12:25
@DamienHarper Created a sample project using same composer.lock file so you can install same versions. Steps are there in readme file including Testing.
[https://github.com/hardiksinh/audit-test](https://github.com/hardiksinh/audit-test)

**Comment by DamienHarper** [comment] 2019-11-27 12:39
@hardiksinh Thanks, I’ll have a look ASAP

**Comment by DamienHarper** [comment] 2019-11-27 18:56
@hardiksinh Thanks again for the test project, it confirmed what I suspected but couldn't reproduce myself. It should be fixed now. May you have a chance to test once again `event-subscriber-priority` branch and provide me some feedback?

**Comment by hardiksinh** [comment] 2019-11-28 15:43
Yes, this fixes the issue. Thank you very much for your time and efforts.

**Comment by DamienHarper** [comment] 2019-11-28 15:44
You're welcome!

**Closed** 2019-11-28 15:44 UTC
Labels: bug

**Comment by samuel4x4** [comment] 2022-10-12 21:55
For `4.2` version I managed somehow to fix it by overwriting the DoctrineSubscriber priority like this (in my app ./config/services.yaml file):

```
DH\Auditor\Provider\Doctrine\Auditing\Transaction\TransactionManager:
    arguments: ['@DH\Auditor\Provider\Doctrine\DoctrineProvider']

DH\Auditor\Provider\Doctrine\Auditing\Event\DoctrineSubscriber:
    arguments: ['@DH\Auditor\Provider\Doctrine\Auditing\Transaction\TransactionManager']
    tags:
        - { name: doctrine.event_subscriber, priority: 1000 }
```

This results in having on the audit table a `remove` entry with the soft deleted object, it's a working solution for me. The perfect solution will be actually to have an `update` entry with the old and new values for the `deletedAt` property, but I couldn't manage to have this, if someone have more success, please post the solution.

**Comment by RomanApunts** [comment] 2023-10-18 14:51
> For `4.2` version I managed somehow to fix it by overwriting the DoctrineSubscriber priority like this (in my app ./config/services.yaml file):
> 
> ```
> DH\Auditor\Provider\Doctrine\Auditing\Transaction\TransactionManager:
>     arguments: ['@DH\Auditor\Provider\Doctrine\DoctrineProvider']
> 
> DH\Auditor\Provider\Doctrine\Auditing\Event\DoctrineSubscriber:
>     arguments: ['@DH\Auditor\Provider\Doctrine\Auditing\Transaction\TransactionManager']
>     tags:
>         - { name: doctrine.event_subscriber, priority: 1000 }
> ```
> 
> This results in having on the audit table a `remove` entry with the soft deleted object, it's a working solution for me. The perfect solution will be actually to have an `update` entry with the old and new values for the `deletedAt` property, but I couldn't manage to have this, if someone have more success, please post the solution.

Doing this one i get duplicated registry of audit remove entity
![image](https://github.com/DamienHarper/auditor-bundle/assets/62882223/6d4514aa-7a2a-403b-9f93-b61c2b28f08c)
